Donovan Griego
Lab 5
10-13-2020

Script started on 2020-10-13 22:31:19-06:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="191" LINES="14"]
]0;dxgriego@Parallels: ~/cse113/lab5[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab5[00m$ gcc -g -Wall lab5_q2.c
]0;dxgriego@Parallels: ~/cse113/lab5[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab5[00m$ ./lab5_q2 
RED: 18
ORANGE: 19
YELLOW: 5
GREEN: 6
BLUE: 7
INDIGO: 14
VIOLET: 15
]0;dxgriego@Parallels: ~/cse113/lab5[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab5[00m$ exit
exit

Script done on 2020-10-13 22:31:42-06:00 [COMMAND_EXIT_CODE="0"]
