Donovan Griego
Lab 5
10-13-2020

Script started on 2020-10-14 00:03:38-06:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="191" LINES="14"]
]0;dxgriego@Parallels: ~/cse113/lab5[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab5[00m$ gcc -g -Wall g[Klab5_q4.c -o lab5_q4
]0;dxgriego@Parallels: ~/cse113/lab5[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab5[00m$ ./lab5_q4
Enter a date in the following format MM/DD/YY: 05/17/02
May 17, Taurus
----Menu----
1. Enter another date
2. Quit
Enter your selection: 1
Enter a date in the following format MM/DD/YY: 02/24/01
February 24, Pisces
----Menu----
1. Enter another date
2. Quit
Enter your selection: 2
Goodbye!
]0;dxgriego@Parallels: ~/cse113/lab5[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab5[00m$ exit
exit

Script done on 2020-10-14 00:04:33-06:00 [COMMAND_EXIT_CODE="0"]
